services:
  # A Python web service
  - type: web
    name: multi-agent-war-simulation
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 