services:
  # A Python web service
  - type: web
    name: multi-agent-war-simulation
    env: python
    plan: free
    buildCommand: sudo ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src 