services:
  # A Python web service
  - type: web
    name: multi-agent-war-simulation
    env: python
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: ./
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: true 