# This workflow builds and deploys a Python Flask app to Azure App Service using a Service Principal and Azure CLI zip deploy.
# It stops using the built-in azure/webapps-deploy action to avoid 409 lock conflicts.

name: Build and deploy Python app to Azure Web App

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: multi-agent-rl-war    # your Azure Web App name
  AZURE_RESOURCE_GROUP: rg-multi-agent-rl-war  # your Resource Group name
  PYTHON_VERSION: '3.9'                    # Python version

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          zip -r release.zip . -x "venv/*" ".git/*" ".github/*" "__pycache__/*" "*.pyc" "test_env/*" ".DS_Store"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop App Service
        run: |
          az webapp stop --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Deploy via Azure CLI ZIP Deploy
        run: |
          az webapp deployment source config-zip \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --src release.zip

      - name: Restart App Service
        run: |
          az webapp start --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Verify deployment
        run: |
          echo "App URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          curl -f https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net || exit 1
